import { Buyer } from '../types/user';

export const mockBuyers: Buyer[] = [
  {
    id: 'b1',
    email: 'rajesh.traders@gmail.com',
    name: 'Rajesh Verma',
    role: 'buyer',
    phone: '+91 99887 76655',
    avatar: '/placeholder.svg?height=100&width=100',
    businessName: 'Rajesh Traders',
    businessType: 'wholesaler',
    location: {
      lat: 28.7041,
      lng: 77.1025,
      address: 'Azadpur Mandi, Delhi',
      city: 'Delhi',
      state: 'Delhi',
    },
    rating: 4.7,
    totalPurchases: 850000,
    createdAt: new Date('2023-01-10'),
  },
  {
    id: 'b2',
    email: 'fresh.retail@gmail.com',
    name: 'Anita Sharma',
    role: 'buyer',
    phone: '+91 99887 76656',
    avatar: '/placeholder.svg?height=100&width=100',
    businessName: 'Fresh Retail Store',
    businessType: 'retailer',
    location: {
      lat: 19.0760,
      lng: 72.8777,
      address: 'Linking Road, Bandra',
      city: 'Mumbai',
      state: 'Maharashtra',
    },
    rating: 4.9,
    totalPurchases: 420000,
    createdAt: new Date('2023-02-15'),
  },
  {
    id: 'b3',
    email: 'south.foods@gmail.com',
    name: 'Kumar Swamy',
    role: 'buyer',
    phone: '+91 99887 76657',
    avatar: '/placeholder.svg?height=100&width=100',
    businessName: 'South Foods Processing',
    businessType: 'processor',
    location: {
      lat: 13.0827,
      lng: 80.2707,
      address: 'Industrial Area, Guindy',
      city: 'Chennai',
      state: 'Tamil Nadu',
    },
    rating: 4.6,
    totalPurchases: 1200000,
    createdAt: new Date('2022-11-20'),
  },
  {
    id: 'b4',
    email: 'global.exports@gmail.com',
    name: 'Meena Desai',
    role: 'buyer',
    phone: '+91 99887 76658',
    avatar: '/placeholder.svg?height=100&width=100',
    businessName: 'Global Agri Exports',
    businessType: 'exporter',
    location: {
      lat: 23.0225,
      lng: 72.5714,
      address: 'GIDC, Vatva',
      city: 'Ahmedabad',
      state: 'Gujarat',
    },
    rating: 4.8,
    totalPurchases: 2500000,
    createdAt: new Date('2022-08-12'),
  },
  {
    id: 'b5',
    email: 'mega.mart@gmail.com',
    name: 'Priya Singh',
    role: 'buyer',
    phone: '+91 99887 76659',
    avatar: '/placeholder.svg?height=100&width=100',
    businessName: 'MegaMart Supermarket',
    businessType: 'retailer',
    location: {
      lat: 12.9716,
      lng: 77.5946,
      address: 'MG Road, Bangalore',
      city: 'Bangalore',
      state: 'Karnataka',
    },
    rating: 4.5,
    totalPurchases: 680000,
    createdAt: new Date('2023-03-08'),
  },
];

export const getCurrentBuyer = (): Buyer => mockBuyers[0];
