import { Farmer } from '../types/user';

export const mockFarmers: Farmer[] = [
  {
    id: 'f1',
    email: 'ravi.kumar@gmail.com',
    name: 'Ravi Kumar',
    role: 'farmer',
    phone: '+91 98765 43210',
    avatar: '/placeholder.svg?height=100&width=100',
    farmLocation: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Village Khera, Delhi Road',
      city: 'Delhi',
      state: 'Delhi',
    },
    cropTypes: ['Wheat', 'Rice', 'Vegetables'],
    farmSize: 15,
    rating: 4.8,
    totalSales: 250000,
    createdAt: new Date('2023-01-15'),
    bankInfo: {
      accountNumber: '1234567890',
      ifscCode: 'SBIN0001234',
      bankName: 'State Bank of India',
    },
  },
  {
    id: 'f2',
    email: 'suresh.patel@gmail.com',
    name: 'Suresh Patel',
    role: 'farmer',
    phone: '+91 98765 43211',
    avatar: '/placeholder.svg?height=100&width=100',
    farmLocation: {
      lat: 23.0225,
      lng: 72.5714,
      address: 'Village Narol, SG Highway',
      city: 'Ahmedabad',
      state: 'Gujarat',
    },
    cropTypes: ['Cotton', 'Groundnut', 'Bajra'],
    farmSize: 25,
    rating: 4.6,
    totalSales: 180000,
    createdAt: new Date('2023-02-20'),
  },
  {
    id: 'f3',
    email: 'lakshmi.reddy@gmail.com',
    name: 'Lakshmi Reddy',
    role: 'farmer',
    phone: '+91 98765 43212',
    avatar: '/placeholder.svg?height=100&width=100',
    farmLocation: {
      lat: 17.3850,
      lng: 78.4867,
      address: 'Village Shamshabad',
      city: 'Hyderabad',
      state: 'Telangana',
    },
    cropTypes: ['Rice', 'Tomato', 'Chilli'],
    farmSize: 10,
    rating: 4.9,
    totalSales: 320000,
    createdAt: new Date('2022-11-10'),
  },
  {
    id: 'f4',
    email: 'manjeet.singh@gmail.com',
    name: 'Manjeet Singh',
    role: 'farmer',
    phone: '+91 98765 43213',
    avatar: '/placeholder.svg?height=100&width=100',
    farmLocation: {
      lat: 31.6340,
      lng: 74.8723,
      address: 'Village Rampura, GT Road',
      city: 'Amritsar',
      state: 'Punjab',
    },
    cropTypes: ['Wheat', 'Sugarcane', 'Potato'],
    farmSize: 30,
    rating: 4.7,
    totalSales: 450000,
    createdAt: new Date('2022-08-05'),
  },
  {
    id: 'f5',
    email: 'ganesh.naik@gmail.com',
    name: 'Ganesh Naik',
    role: 'farmer',
    phone: '+91 98765 43214',
    avatar: '/placeholder.svg?height=100&width=100',
    farmLocation: {
      lat: 19.0760,
      lng: 72.8777,
      address: 'Village Malad, Western Express Highway',
      city: 'Mumbai',
      state: 'Maharashtra',
    },
    cropTypes: ['Onion', 'Cabbage', 'Cauliflower'],
    farmSize: 8,
    rating: 4.5,
    totalSales: 150000,
    createdAt: new Date('2023-03-12'),
  },
];

export const getCurrentFarmer = (): Farmer => mockFarmers[0];
