export const mockTransportRequests = [
  {
    id: 'tr-1',
    orderId: 'order-1',
    status: 'pending',
    pickupLocation: {
      address: 'Farm Road',
      city: 'Amritsar',
      state: 'Punjab',
      pincode: '143001',
    },
    deliveryLocation: {
      address: 'Market Street',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110001',
    },
    distance: 450,
    vehicleType: 'Truck',
    pickupDate: '2024-06-20',
    price: 8500,
    weight: 5000,
  },
  {
    id: 'tr-2',
    orderId: 'order-2',
    status: 'accepted',
    pickupLocation: {
      address: 'Village Road',
      city: 'Hisar',
      state: 'Haryana',
      pincode: '125001',
    },
    deliveryLocation: {
      address: 'Commercial Zone',
      city: 'Gurgaon',
      state: 'Haryana',
      pincode: '122001',
    },
    distance: 165,
    vehicleType: 'Mini Truck',
    pickupDate: '2024-06-18',
    price: 3200,
    weight: 1500,
  },
  {
    id: 'tr-3',
    orderId: 'order-3',
    status: 'in_transit',
    pickupLocation: {
      address: 'Farm Lane',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
    },
    deliveryLocation: {
      address: 'Industrial Area',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
    },
    distance: 150,
    vehicleType: 'Tempo',
    pickupDate: '2024-06-17',
    price: 2800,
    weight: 800,
  },
  {
    id: 'tr-4',
    orderId: 'order-4',
    status: 'delivered',
    pickupLocation: {
      address: 'Village Center',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302001',
    },
    deliveryLocation: {
      address: 'Market Complex',
      city: 'Ajmer',
      state: 'Rajasthan',
      pincode: '305001',
    },
    distance: 135,
    vehicleType: 'Mini Truck',
    pickupDate: '2024-06-15',
    price: 2500,
    weight: 1200,
  },
  {
    id: 'tr-5',
    orderId: 'order-5',
    status: 'pending',
    pickupLocation: {
      address: 'Farm House',
      city: 'Nashik',
      state: 'Maharashtra',
      pincode: '422001',
    },
    deliveryLocation: {
      address: 'Wholesale Market',
      city: 'Surat',
      state: 'Gujarat',
      pincode: '395001',
    },
    distance: 280,
    vehicleType: 'Truck',
    pickupDate: '2024-06-21',
    price: 5600,
    weight: 3500,
  },
  {
    id: 'tr-6',
    orderId: 'order-6',
    status: 'pending',
    pickupLocation: {
      address: 'Village Square',
      city: 'Ludhiana',
      state: 'Punjab',
      pincode: '141001',
    },
    deliveryLocation: {
      address: 'Trade Center',
      city: 'Chandigarh',
      state: 'Chandigarh',
      pincode: '160001',
    },
    distance: 95,
    vehicleType: 'Mini Truck',
    pickupDate: '2024-06-22',
    price: 1800,
    weight: 900,
  },
];
